node_js: "8"
cache:
  yarn: true
  directories:
    - node_modules
    - ios/build
    - ios/Pods
branches:
  only:
  - gh-pages
  - /.*/
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      env:
        - IOS_CONFIGURATION=Release
before_install:
  - travis_retry npm install -g yarn
  - cd ios && pod install && cd ..
install:
  - travis_retry yarn
script:
  - yarn appium --log-level error &
  - yarn xcodebuild -configuration $IOS_CONFIGURATION > ios/build/xcodebuild.log
  - IOS_DEVICE_NAME="iPhone 5s" yarn test-and-shutdown-ios-simulator
  - IOS_DEVICE_NAME="iPhone 6" yarn test-and-shutdown-ios-simulator
  - IOS_DEVICE_NAME="iPhone 6 Plus" yarn test-and-shutdown-ios-simulator
  - IOS_DEVICE_NAME="iPhone X" yarn test-and-shutdown-ios-simulator
before_deploy:
  - git status --short
deploy:
  provider: pages
  local-dir: .
  target-branch: verify-screenshot-with-appium
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch:
      - verify-screenshot-with-appium
