cache:
  yarn: true
  directories:
    - node_modules
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.4
      node_js:
        - "8"
      before_install:
        - nvm install 8
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry yarn
      script:
        - yarn test
