language: node_js
node_js:
    - "5.6.0"
install:
    - npm install
script:
    - npm test
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
".travis.yml" 6L, 63C written
