language: android
env:
  matrix:
    - ANDROID_TARGET=22
    - ANDROID_TARGET=23
    - ANDROID_TARGET=24
    - ANDROID_TARGET=25
    - ANDROID_TARGET=26
    - ANDROID_TARGET=27
    - ANDROID_TARGET=28
android:
  components:
    - build-tools-$ANDROID_TARGET.0.1
    - android-$ANDROID_TARGET
    - sys-img-armeabi-v7a-android-$ANDROID_TARGET
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-$ANDROID_TARGET --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - adb devices
