node_js: "8"
  
cache:
  yarn: true
  directories:
    - node_modules
    - ios/build
    - ios/Pods
    
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      env:
        - IOS_CONFIGURATION=Release
        - IOS_DEVICE_NAME="iPhone 6"
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      env:
        - IOS_CONFIGURATION=Release
        - IOS_DEVICE_NAME="iPhone X"
      
before_install:
  - travis_retry npm install -g yarn
  - cd ios && pod install && cd ..
  
install:
  - travis_retry yarn
  
script:
  - yarn appium --log-level error &
  - yarn xcodebuild -configuration $IOS_CONFIGURATION > xcodebuild.log
  - yarn test

before_deploy:
  - echo -e "machine github.com\n  login $GITHUB_USER\n  password $GITHUB_USER_PASSWORD" >~/.netrc
deploy:
  - git add screenshots/*
  - git commit -m 'Update screenshots'
  - git push
after_deploy:
  - ./after_deploy_1.sh
  - ./after_deploy_2.sh
  