language: android
android:
  components:
    - build-tools-28.0.1
    - android-26
    - sys-img-armeabi-v7a-android-26
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - adb devices
