node_js: "8"
podfile: ios/Podfile
  
cache:
  yarn: true
  directories:
    - node_modules
    - ios/build
    - ios/Pods
    
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      env:
        - IOS_CONFIGURATION=Release
        - IOS_DEVICE_NAME="iPhone 6"
      
before_install:
  - travis_retry npm install -g yarn
  
install:
  - travis_retry yarn
  
script:
  - yarn appium --log-level error &
  - pod install
  - yarn xcodebuild -configuration $IOS_CONFIGURATION > xcodebuild.log
  - yarn test
