language: node_js
node_js:
  - "7"
install:
    - npm install
script:
    - npm test
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
".travis.yml" 6L, 63C written
