node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
    - ios/build
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      env:
        - IOS_CONFIGURATION=Release
before_install:
  - npm install -g yarn
install:
  - yarn install
script:
  - yarn appium --log-level error &
  - yarn xcodebuild -configuration $IOS_CONFIGURATION > xcodebuild.log
  - yarn test
