deploy:
  provider: pages
  local-dir: .
  target-branch: deploy-github-pages-from-travis
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch:
      - deploy-github-pages-from-travis
