matrix:
    include:
        - language: objective-c
          os: osx
          osx_image: xcode9.4
          node_js: "7"
          before_install:
              - node --version
          install:
              - npm install
          script:
              - npm test
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
".travis.yml" 6L, 63C written
