branches:
  only:
  - gh-pages
  - /.*/
  
node_js:
  - "8"
  
cache:
  yarn: true
  directories:
    - node_modules
    
before_install:
  - travis_retry npm install -g yarn
  
install:
  - travis_retry yarn
  
script:
  - yarn test

after_success:
  - mkdir docs
  - cp README.md docs/

deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
