branches:
  only:
  - gh-pages
  - /.*/
  
node_js:
  - "8"
  
cache:
  yarn: true
  directories:
    - node_modules
    
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      
before_install:
  - travis_retry npm install -g yarn
  - yarn appium --log-level error &
  
install:
  - travis_retry yarn
  
script:
  - yarn test

before_deploy:
  - mkdir gh-pages
  - mv screenshots gh-pages/

deploy:
  provider: pages
  local-dir: gh-pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch:
      - master
      - travis-deploy-gh-pages
