matrix:
    include:
        - os: osx
          language: objective-c
install:
    - npm install
script:
    - npm test
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
".travis.yml" 6L, 63C written
