node_js: "8"
  
cache:
  yarn: true
  directories:
    - node_modules
    - ios/build
    - ios/Pods
    
branches:
  only:
  - gh-pages
  - /.*/
  
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      env:
        - IOS_CONFIGURATION=Release
        - IOS_DEVICE_NAME="iPhone 6"
    - os: osx
      osx_image: xcode9.4
      language: objective-c
      env:
        - IOS_CONFIGURATION=Release
        - IOS_DEVICE_NAME="iPhone X"
      
before_install:
  - travis_retry npm install -g yarn
  - cd ios && pod install && cd ..
  - git submodule add -f -b gh-pages "https://github.com/blcsntb/BReactNative.git" screenshots
  
install:
  - travis_retry yarn
  
script:
  - yarn appium --log-level error &
  - yarn xcodebuild -configuration $IOS_CONFIGURATION > xcodebuild.log
  - yarn test

before_deploy:
  - git submodule update

deploy:
  provider: pages
  local-dir: screenshots
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch:
      - master
      - feature/appium-screenshot
