node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
    - ios/build
env:
  - IS_RELEASE=true
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: objective-c
before_install:
  - npm install -g yarn
install:
  - yarn install
script:
  - yarn test
  - yarn appium --log-level error &
  - yarn build-ios-release > ios/build/xcodebuild.log
  - yarn e2e-ios
