matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.0
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry yarn
      script:
        - yarn test
