node_js:
  - "8"
  
cache:
  yarn: true
  directories:
    - node_modules
    
before_install:
  - node --version
  - travis_retry npm install -g yarn
  - yarn -version
  
install:
  - travis_retry yarn
  
script:
  - yarn test
